jobs:
  include:
    - os: freebsd
      language: python
      script:
        - python hw.py
    - os: linux
      dist: focal
      arch: amd64
      virt: lxd
      group: dev
      language: python
      script:
        - uname -m
        - python hw.py
